### ISSUE TITLE
kinda stupid

### ISSUE THREAD

**Issue by Gingeropolous** [ShenNoether/MiniNodo#4]
But when you send to a btc address (via xmr.to), its not entirely clear that you should enter the btc amount (not the xmr amount).

I guess I'm monero-centric, so I assumed I should still enter the monero amount.... and then the dialog box popped up and asked me if I wanted to send 483 xmr....

**Comment by ShenNoether** [comment]
I will make it more clear by updating the placeholder text to "amount in btc or xmr (depending on above)" - I just assumed that most places asking for a bitcoin address would supply a desired bitcoin amount (e.g. my typical use cases are something like https://coffee.foldapp.com/, givedirectly, bitpay checkout etc, where an amount in bitcoin is requested)

**Comment by ShenNoether** [comment]
Updated: https://github.com/ShenNoether/MiniNodo/commit/41549e06afbd925e71eb73cb395407f650af0ad5
