### ISSUE TITLE
request: on startup, move password to file or flag

### ISSUE THREAD

**Issue by Gingeropolous** [ShenNoether/MiniNodo#5]
if MiniNodo is daemonized via upstart or whatever, the prompt for a password is unusable. Is it possible to put it as a flag or store it as a file?

**Comment by ShenNoether** [comment]
Yes I've added the -p flag for password, -mp for setting the port that the app is accessible on, and -swp for setting the port that simplewallet listens on via the minimist module: https://github.com/ShenNoether/MiniNodo/commit/74c94426e263a888d196ea1c71209bc9de474b6c
